using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Newtonsoft.Json.Linq;

namespace GxMcp.Worker.Services
{
    public class GxTestCase
    {
        public string Name { get; set; }
        public string CaseType { get; set; } // HappyPath | Boundary | ErrorCase
        public string Description { get; set; }
        public JObject Inputs { get; set; }
        public JObject ExpectedOutputs { get; set; }

        public GxTestCase()
        {
            Name = string.Empty;
            CaseType = "HappyPath";
            Description = string.Empty;
            Inputs = new JObject();
            ExpectedOutputs = new JObject();
        }
    }

    public class GxUnitTestPlan
    {
        public string TargetObject { get; set; }
        public string TestObjectName { get; set; }
        public List<GxTestCase> TestCases { get; set; }
        public JObject Variables { get; set; }
        public string GeneratedRules { get; set; }
        public string GeneratedSource { get; set; }

        public GxUnitTestPlan()
        {
            TargetObject = string.Empty;
            TestObjectName = string.Empty;
            TestCases = new List<GxTestCase>();
            Variables = new JObject();
            GeneratedRules = string.Empty;
            GeneratedSource = string.Empty;
        }
    }

    public static class GxTestGeneratorService
    {
        public static GxUnitTestPlan GenerateUnitTestCode(
            string targetProcName,
            List<ApiIntrospectService.Parm> parms,
            bool useGxTestAssertModule = false)
        {
            var plan = new GxUnitTestPlan
            {
                TargetObject = targetProcName,
                TestObjectName = $"Test_{targetProcName}",
                GeneratedRules = "// Standalone test runner — no parm rule"
            };

            var sb = new StringBuilder();
            sb.AppendLine($"// ============================================================================");
            sb.AppendLine($"// Automated Unit Test for Procedure: {targetProcName}");
            sb.AppendLine($"// Generated by Genexus18MCP GxTestGeneratorService");
            sb.AppendLine($"// ============================================================================");
            sb.AppendLine();

            var inParms = (parms ?? new List<ApiIntrospectService.Parm>())
                .Where(p => string.Equals(p.Direction, "in", StringComparison.OrdinalIgnoreCase) || string.Equals(p.Direction, "inout", StringComparison.OrdinalIgnoreCase))
                .ToList();

            var outParms = (parms ?? new List<ApiIntrospectService.Parm>())
                .Where(p => string.Equals(p.Direction, "out", StringComparison.OrdinalIgnoreCase) || string.Equals(p.Direction, "inout", StringComparison.OrdinalIgnoreCase))
                .ToList();

            // Populate variables
            foreach (var p in (parms ?? new List<ApiIntrospectService.Parm>()))
            {
                string varName = NormalizeVarName(p.Name);
                plan.Variables[varName] = p.Type ?? "Character";
            }

            // Case 1: Happy Path
            var happyCase = new GxTestCase
            {
                Name = "TestCase_Success",
                CaseType = "HappyPath",
                Description = "Valid input execution test case"
            };
            plan.TestCases.Add(happyCase);

            // In GeneXus Procedures, top-level procedural statements MUST precede all Sub definitions (src0089 guard)
            sb.AppendLine("// --- Test Runner Entrypoint ---");
            sb.AppendLine("Do 'Test_HappyPath'");
            if (inParms.Count > 0)
            {
                var boundaryCase = new GxTestCase
                {
                    Name = "TestCase_Boundary",
                    CaseType = "Boundary",
                    Description = "Boundary input (zero / empty) test case"
                };
                plan.TestCases.Add(boundaryCase);
                sb.AppendLine("Do 'Test_Boundary'");
            }
            sb.AppendLine();

            // --- Subroutines ---
            string callArgs = string.Join(", ", (parms ?? new List<ApiIntrospectService.Parm>()).Select(p => NormalizeVarName(p.Name)));

            // Sub 'Test_HappyPath'
            sb.AppendLine("// --- Test Case 1: Happy Path ---");
            sb.AppendLine("Sub 'Test_HappyPath'");
            foreach (var p in inParms)
            {
                string varName = NormalizeVarName(p.Name);
                sb.AppendLine($"    {varName} = {GetSampleValueForType(p.Type, 1)}");
            }

            sb.AppendLine($"    {targetProcName}.Call({callArgs})");

            foreach (var p in outParms)
            {
                string varName = NormalizeVarName(p.Name);
                string assertion = BuildAssertionForType(varName, p.Type, useGxTestAssertModule);
                sb.AppendLine($"    {assertion}");
            }
            sb.AppendLine("EndSub");
            sb.AppendLine();

            // Sub 'Test_Boundary'
            if (inParms.Count > 0)
            {
                sb.AppendLine("// --- Test Case 2: Boundary / Null Input ---");
                sb.AppendLine("Sub 'Test_Boundary'");
                foreach (var p in inParms)
                {
                    string varName = NormalizeVarName(p.Name);
                    sb.AppendLine($"    {varName} = {GetDefaultValueForType(p.Type)}");
                }

                sb.AppendLine($"    {targetProcName}.Call({callArgs})");
                sb.AppendLine("EndSub");
                sb.AppendLine();
            }

            plan.GeneratedSource = sb.ToString();
            return plan;
        }

        private static string NormalizeVarName(string rawName)
        {
            if (string.IsNullOrWhiteSpace(rawName)) return "&Param";
            string clean = rawName.Trim();
            return clean.StartsWith("&") ? clean : "&" + clean;
        }

        private static string BuildAssertionForType(string varName, string type, bool useGxTestAssertModule)
        {
            string clean = (type ?? "Character").ToLowerInvariant();

            if (useGxTestAssertModule)
            {
                if (clean.Contains("bool"))
                    return $"Assert.IsTrue({varName}, 'Expected {varName} to be true on successful run')";
                if (clean.Contains("sdt:messages"))
                    return $"Assert.AreEqual(0, {varName}.Count, 'Expected 0 error messages on success')";
                if (clean.StartsWith("num") || clean == "int")
                    return $"Assert.IsTrue({varName} >= 0, 'Expected valid numeric result for {varName}')";
                if (clean.StartsWith("char") || clean.StartsWith("varchar"))
                    return $"Assert.IsTrue({varName} <> '', 'Expected non-empty character result for {varName}')";
                if (clean == "date" || clean == "datetime")
                    return $"Assert.IsTrue(not {varName}.IsEmpty(), 'Expected valid date result for {varName}')";
                return $"Assert.IsNotNull({varName}, 'Expected {varName} not null')";
            }

            // Universal GeneXus assertion (zero external dependencies, runs on any KB)
            if (clean.Contains("bool"))
                return $"if not ({varName})\n        msg('ASSERTION FAILED: Expected {varName} to be true', status)\n    endif";
            if (clean.Contains("sdt:messages"))
                return $"if ({varName}.Count > 0)\n        msg('ASSERTION FAILED: Expected 0 error messages', status)\n    endif";
            if (clean.StartsWith("num") || clean == "int")
                return $"if not ({varName} >= 0)\n        msg('ASSERTION FAILED: Expected valid numeric result for {varName}', status)\n    endif";
            if (clean.StartsWith("char") || clean.StartsWith("varchar"))
                return $"if ({varName} = '')\n        msg('ASSERTION FAILED: Expected non-empty character result for {varName}', status)\n    endif";
            if (clean == "date" || clean == "datetime")
                return $"if ({varName}.IsEmpty())\n        msg('ASSERTION FAILED: Expected valid date result for {varName}', status)\n    endif";
            return $"if ({varName}.IsNull())\n        msg('ASSERTION FAILED: Expected {varName} not null', status)\n    endif";
        }

        private static string GetSampleValueForType(string type, int id)
        {
            string clean = (type ?? "Character").ToLowerInvariant();
            if (clean.StartsWith("num") || clean == "int")
                return id.ToString();
            if (clean == "boolean" || clean == "bool")
                return "True";
            if (clean == "date")
                return "#2026-01-01#";
            if (clean == "datetime")
                return "#2026-01-01 12:00:00#";
            return $"'TEST_{id}'";
        }

        private static string GetDefaultValueForType(string type)
        {
            string clean = (type ?? "Character").ToLowerInvariant();
            if (clean.StartsWith("num") || clean == "int")
                return "0";
            if (clean == "boolean" || clean == "bool")
                return "False";
            if (clean == "date" || clean == "datetime")
                return "NullValue(DateTime.Now())";
            return "''";
        }
    }
}
